### ISSUE TITLE
Previous input remains

### ISSUE THREAD

**Issue by PhillipVas** [itsjustmustafa/sorcerdle#2]
After clicking the input box, the text of the previous entry remains. This is highly disconcerting and greatly affects my ability to focus on what my next guess will be.

**Comment by itsjustmustafa** [comment]
did you thumbs up your own issue phil?

**Comment by PhillipVas** [comment]
It's important to me

**Comment by PhillipVas** [comment]
Hey guys, any update? Really hoping you havn't given up on this!

**Comment by PhillipVas** [comment]
...given up on me

**Comment by itsjustmustafa** [comment]
Following a thorough engagement with our external subject-matter expert and after conducting an in-depth analysis aligned with our core operational parameters, it has been determined that the proposed task does not fall within the realm of executable deliverables at this time.

This conclusion was reached after a rigorous evaluation of all potential pathways, weighing resource allocation against strategic objectives, and benchmarking against industry standards. Unfortunately, the inherent complexities and current constraints preclude the realization of this initiative in its present form.

We remain committed to exploring alternative opportunities that align more seamlessly with our capabilities and overarching goals.

Warm regards,
The Sorcerdle Team
